services:
  - type: web
    name: proyectoSimulacion
    env: node
    buildCommand: |
      npm install --prefix client --legacy-peer-deps
      npm run build --prefix client
      npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_VERSION
        value: 18

